config/routes.rb
Rails.application.routes.draw do
  resources :bases, only: [:index, :create, :update, :show, :destory], format: 'json'
  resources :messages, only: [:index, :create, :update, :show, :destroy], format: 'json'
  get 'sample/index'
  get 'sample/show'
  resources :sample
  resources :edits
  get 'about/show' => '/about'
  get 'top/index'
  get 'top/edit'
  get 'top/update'
  root to: 'top#index'
  resources :tops
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/api.rb
module Api
  def self.table_name_prefix
    'api_'
  end
end

app/models/api/v1.rb
module Api::V1
  def self.table_name_prefix
    'api_v1_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basis.rb
class Basis < ApplicationRecord
end

app/models/edit.rb
class Edit < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/top.rb
class Top < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def index
    @users = [
      { name: '前田 幹太', u_name: '会津大学', d_name: 'コンピュータ理工学部'}
    ]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bases_controller.rb
class BasesController < ApplicationController
	before_action :set_edit, only: [:show, :edit, :update, :destory]
	protect_from_forgery :except => [:create, :update, :destroy]
	skip_before_action :verify_authenticity_token

	def index
		base = Basis.all
		render json: base
	end

	def create
		base = Basis.new(base_params)
		if base.save
			render json: base, status: :create
		else
			render json: base, status: :unprocessable_entity
		end
	end

	def show
		@id = "/bases/" + params[:id]
		render json: @base
	end

	def edit
		@id = "/bases/" + params[:id]
		render json: @bases
	end

	def update
	    if @base.update(base_params)
	      	render json: @base, status: :ok
	      	#redirect_to "/"
	    else
	    	render json: base, status: :unprocessable_entity
	    end
	   
	end

	def destroy
		base = Basis.find(params[:id])
		base.destroy
		#head :no_content
		#render json: base, status: :ok
		render :template => "sample/index"
	end

	private
		def set_edit
	      @base = Basis.find(params[:id])
	    end

		def base_params
			params.permit(:name, :furigana, :university, :department, :subject, :graduate_year, :email, :tel, :github, :facebook, :twitter)
		end

end

app/controllers/edits_controller.rb
class EditsController < ApplicationController
  before_action :set_edit, only: [:show, :edit, :update, :destroy]

  # GET /edits
  # GET /edits.json
  def index
    @edits = Edit.all
  end

  # GET /edits/1
  # GET /edits/1.json
  def show
  end

  # GET /edits/new
  def new
    @edit = Edit.new
  end

  # GET /edits/1/edit
  def edit
  end

  # POST /edits
  # POST /edits.json
  def create
    @top = Top.new(edit_params)

    respond_to do |format|
      if @top.save
        format.html { redirect_to @top, notice: 'Edit was successfully created.' }
        format;js 
        format.json { render json: @top }
      else
        format.html { render :new }
        format.json { render json: @top.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /edits/1
  # PATCH/PUT /edits/1.json
  def update
    respond_to do |format|
      if @edit.update(edit_params)
        format.html { redirect_to @edit, notice: 'Edit was successfully updated.' }
        format.json { render :show, status: :ok, location: @edit }
      else
        format.html { render :edit }
        format.json { render json: @edit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /edits/1
  # DELETE /edits/1.json
  def destroy
    @edit.destroy
    respond_to do |format|
      format.html { redirect_to edits_url, notice: 'Edit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_edit
      @edit = Edit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def edit_params
      params.require(:top).permit(:name)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :set_edit, only: [:show, :edit, :update, :destory]
	protect_from_forgery :except => [:create, :update, :destroy]
	skip_before_action :verify_authenticity_token

	def index
		messages = Message.all
		render json: messages
	end

	def create
		message = Message.new(message_params)
		if message.save
			render json: message, status: :create
		else
			render json: message, status: :unprocessable_entity
		end
	end

	def show
		@id = "/messages/" + params[:id]
		render json: @message
	end

	def edit
		@id = "/messages/" + params[:id]
		render json: @messages
	end

	def update
	    if @message.update(message_params)
	      	render json: @message, status: :ok
	    else
	    	render json: message, status: :unprocessable_entity
	    end
	   
	end

	def destroy
		message = Message.find(params[:id])
		message.destroy
		#head :no_content
		#render json: message, status: :ok
		render :template => "sample/index"
	end

	private
		def set_edit
	      @message = Message.find(params[:id])
	    end

		def message_params
			params.permit(:user, :text, :id)
		end

end

app/controllers/sample_controller.rb
class SampleController < ApplicationController
  def index
  end

  def show
  	@id = "/messages/" + params[:id]
  end

  def edit
  	@id = "/messages/" + params[:id]
  end

  def destory
  	message = Message.find(params[:id])
  	message.destroy
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  	@top = Top.find(1)
  end

  def edit
  	@top = Top.find(1)
  end

  def new
    @edit = Edit.new
  end

  def create
    @top = Top.new(edit_params)

    respond_to do |format|
      if @top.save
        format.html { redirect_to @top, notice: 'Edit was successfully created.' }
        format;js 
        format.json { render json: @top }
      else
        format.html { render :new }
        format.json { render json: @top.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @edit.update(edit_params)
        format.html { redirect_to @top, notice: 'Edit was successfully updated.' }
        format.js
        format.json { render json: @top }
      else
        format.html { render :top }
        format.json { render json: @top.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_edit
      @edit = Edit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def edit_params
      params.require(:top).permit(:name)
    end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bases_helper.rb
module BasesHelper
end

app/helpers/edits_helper.rb
module EditsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sample_helper.rb
module SampleHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/edits/_form.html.erb
<%= form_with(model: edit, local: true) do |form| %>
  <% if edit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(edit.errors.count, "error") %> prohibited this edit from being saved:</h2>

      <ul>
      <% edit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_name %>
    <%= form.text_field :user_name %>
  </div>

  <div class="field">
    <%= form.label :phonetic %>
    <%= form.text_field :phonetic %>
  </div>

  <div class="field">
    <%= form.label :department %>
    <%= form.text_field :department %>
  </div>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :facebook %>
    <%= form.text_field :facebook %>
  </div>

  <div class="field">
    <%= form.label :github %>
    <%= form.text_field :github %>
  </div>

  <div class="field">
    <%= form.label :twitter %>
    <%= form.text_field :twitter %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/edits/edit.html.erb
<h1>Editing Edit</h1>

<%= render 'form', edit: @edit %>

<%= link_to 'Show', @edit %> |
<%= link_to 'Back', edits_path %>

app/views/edits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Edits</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Phonetic</th>
      <th>Department</th>
      <th>Subject</th>
      <th>Email</th>
      <th>Image</th>
      <th>Facebook</th>
      <th>Github</th>
      <th>Twitter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @edits.each do |edit| %>
      <tr>
        <td><%= edit.user_name %></td>
        <td><%= edit.phonetic %></td>
        <td><%= edit.department %></td>
        <td><%= edit.subject %></td>
        <td><%= edit.email %></td>
        <td><%= edit.image %></td>
        <td><%= edit.facebook %></td>
        <td><%= edit.github %></td>
        <td><%= edit.twitter %></td>
        <td><%= link_to 'Show', edit %></td>
        <td><%= link_to 'Edit', edit_edit_path(edit) %></td>
        <td><%= link_to 'Destroy', edit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Edit', new_edit_path %>

app/views/edits/new.html.erb
<h1>New Edit</h1>

<%= form_with(model: @edit, local: true) do |form| %>
  <%= react_component('Edit', edit: @edit) %>
<% end %>

<%= link_to 'Back', edits_path %>

app/views/edits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @edit.user_name %>
</p>

<p>
  <strong>Phonetic:</strong>
  <%= @edit.phonetic %>
</p>

<p>
  <strong>Department:</strong>
  <%= @edit.department %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @edit.subject %>
</p>

<p>
  <strong>Email:</strong>
  <%= @edit.email %>
</p>

<p>
  <strong>Image:</strong>
  <%= @edit.image %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @edit.facebook %>
</p>

<p>
  <strong>Github:</strong>
  <%= @edit.github %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @edit.twitter %>
</p>


<%= link_to 'Edit', edit_edit_path(@edit) %> |
<%= link_to 'Back', edits_path %>

app/views/messages/edit.html.erb
<h1>Sample#show</h1>
<p>Find me in app/views/messages/show.html.erb</p>
<%= react_component("sample_edit", url: @id ) %>

app/views/messages/index.html.erb
<h1>Sample#index</h1>
<p>Find me in app/views/messages/index.html.erb</p>
<%= react_component("sample", url: "/messages") %>

app/views/messages/show.html.erb
<h1>Sample#show</h1>
<p>Find me in app/views/messages/show.html.erb</p>
<%= react_component("sample_edit", url: @id ) %>

app/views/top/edit.html.erb
<%= react_component("edit", name: @top.name) %>

app/views/top/index.html.erb
<%= react_component("top", name: @top.name, u_name: @top.u_name, d_name: @top.d_name, gender: @top.gender, birthday: @top.birthday, graduate: @top.graduate, birthplace: @top.birthplace, highschool: @top.highschool, licenses: @top.licenses, hobby: @top.hobby) %>